
version: 1
from: "infracamp/kickstart-flavor-gaia:testing"

apache_fallback_resource: "/index.php"
http_port: 80


config_file:
  template: "config.php.dist"
  target: "config.php"


command:
  build:
    - "echo \"www-data   ALL = (ALL) NOPASSWD: /usr/bin/docker\" | sudo tee --append /etc/sudoers"
    - sudo scripts/install.sh
    - "composer update"

  dev:
    - sudo /opt/scripts/startup.sh

  run:
    - sudo /opt/scripts/startup.sh

  interval:
    - sudo php -f /opt/bin/acquire-ssl-certs.php || sleep 60

